name: Portfolio CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Verify
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Docker Compose Build
        run: docker compose build
        # Mục đích của bước này là để đảm bảo code không bị lỗi compile (do build Docker image thất bại) trước khi tiến hành deploy lên server thật.

  deploy:
    name: Deploy Local Machine
    needs: build
    runs-on: self-hosted
    
    steps:
      - name: Pull and Deploy
        run: |
          cd C:\Users\khoi\Desktop\Portfolio
          git pull origin main
          docker compose up --build -d
          docker image prune -f

