name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          $envContent = @"
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
          GRAFANA_PASSWORD=${{ secrets.GRAFANA_PASSWORD }}
          MINIO_ROOT_USER=${{ secrets.MINIO_ROOT_USER }}
          MINIO_ROOT_PASSWORD=${{ secrets.MINIO_ROOT_PASSWORD }}
          MAIL_APP_PASSWORD=${{ secrets.MAIL_APP_PASSWORD }}
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}
          VITE_API_URL=http://171.233.238.34:5000
          "@
          Set-Content -Path .env -Value $envContent -Encoding UTF8

      - name: Build and Deploy via Docker Compose
        run: |
          # Stop old containers
          docker compose down
          # Build and start new containers
          docker compose up --build -d
          # Clean up old dangling images to save disk space
          docker image prune -f
